### ISSUE TITLE
How do you transfer to a remote server where the file does not exist yet ?

### ISSUE THREAD

**Issue by lowks** [mikejdorm/sftp_ex#7]
Do you have an example where I want to transfer to a remote system where the file does not exist and I do not want to over write any existing file but I want to create a new file ?

Example: 

```
iex(13)> File.stream!("/Users/lowks/work/Radpath/LICENSE") |> Stream.into(SftpEx.stream!(conn, "/home/lowks/LICENSE")) |> Stream.run

13:11:11.334 [error] {:error, :no_such_file}

13:11:11.334 [error] {:error, :no_such_file}
** (BadFunctionError) expected a function, got: :no_such_file
    (elixir) lib/stream.ex:492: Stream.do_into/4
    (elixir) lib/stream.ex:591: Stream.run/1
```

**Comment by lorantkurthy** [comment]
In my pull request #9 this  is fixed.
As a workaround you can run this before streaming the file:

SftpEx.upload(conn,"/home/lowks/LICENSE","")

This will create an empty file on the remote host.

**Comment by janajri** [comment]
Nice fix. Workaround worked perfectly for me.
